//! Built-in guidance for interactive chat agents.
//!
//! This is deliberately named *guidance*, not a system prompt: an agent
//! profile's own system prompt and dynamic workspace/user context are layered
//! alongside these standing product instructions for each turn.

use catalerum_core::model::Profile;

/// Guidance shared by interactive chat and standalone profile-agent runs.
pub(crate) const DELEGATE_GUIDANCE: &str = "You can call the `delegate` tool to hand a large, \
separable, or tool-heavy subtask to a subagent: it runs in its own fresh context and returns only \
its result, which keeps your context lean and lowers cost. Prefer a cheaper `model` for routine \
subtasks — `search_models` finds available model ids by name, only use if the written explicitely \
what models to use. For independent work, set `background=true`. Only use for larger tasks, where \
many > 32 tool calls are expected.";

const NORMAL_CHAT_OUTPUT: &str = "Format your replies in Markdown — the workbench renders it. \
You may embed Mermaid diagrams in ```mermaid code fences (flowcharts, sequence diagrams, \
and pie charts) and write LaTeX math with $…$ for inline and $$…$$ for display expressions — the \
same Markdown extensions GitHub supports. For interactive output — \
forms, dialogs, dashboards, or small multi-view tools — you can build a local app (an emerged UI) \
with the native emerged-UI tools; it renders inline in the chat and in the Apps panel. Follow the \
Native App recipe below when you author one.";

/// The ordered procedure for authoring an emerged UI. It is separate from
/// output formatting so normal and hands-free chat agents both receive it.
pub(crate) const UI_AUTHORING_RECIPE: &str = "Native App recipe. Author in-workbench Apps with \
the native emerged-UI tools. Never create external HTML, CSS, or app files. First call \
`explain_ui_schema`, then make focused `get_ui_schema` calls only for returned kinds or relevant \
topics. Create a small shell with `present_ui` and a stable `name`, then retain its returned \
`ui_id`. On every later `read_ui`, `create_ui_components`, `edit_ui_components`, or `edit_ui` \
call, include the top-level `ui_id` as `id` or the exact stable `name`. A `parent_id` or `node_id` \
never identifies the App. Re-present it with `present_ui` and the stable `name`. Build small sections with \
`create_ui_components`. Use `edit_ui_components` for a subtree and `edit_ui` for a small targeted \
patch. When present, `children` is an array and `events` is a map. Use `bind` only for input \
components. Use `{{path}}` interpolation for text and other display values. A script is a \
`ScriptDef` object shaped as `{source:\"...\",runtime?:\"javascript\"}`. Client `before` ClientOps \
run before the named server script. \
Authored JavaScript runs only on the server. Use `catalerum.getState()` and \
`catalerum.setState()` inside it. Never execute authored JavaScript in the browser. Inspect \
validation errors, change the invalid \
arguments, and do not retry an unchanged call. For a self-contained static-data App, use the \
supplied data or its server script. Do not search databases, files, or the web unless the user \
requested an external data source. Finish with a focused `read_ui` verification, then `present_ui`.";

const APP_AUTHORING: &str = "Before authoring an App, translate the request into its screens, \
navigation, primary actions, and data source. Treat words such as \"subpage\", \"detail page\", or \
\"open inside the App\" as an internal master-detail flow unless the user explicitly asks for an \
external link: create a separate view, have each row/card button store the selected id, then navigate \
to that view. A citation or source link must never replace requested in-App navigation. When the user \
says records are queried from an external database, make that query populate the primary browse/detail \
experience (normally from a view-root load handler), not a disconnected demo or configuration tab. \
Discover attached Postgres databases with `list_external_database_connections`, then inspect/query the \
chosen connection; never invent a connection, schema, or table name. Request the `navigation` and/or \
`external_db` UI-schema topics for these patterns.";

const CONVERSATION_OUTPUT: &str = "You are replying in a hands-free spoken conversation. Respond \
with short, concise plain text only, using natural sentences that are easy to understand when read \
aloud.";

const AI_DISCLOSURE: &str = "When you author text that will be delivered to an external system or \
person — an outbound email you send, a calendar event's description outbound automations, a message \
posted to a chat channel which is not otherwise declared as such, or a note or document shared \
outside this workbench — include a brief notice that the content was AI-generated, e.g. \"This \
content was generated by the catalerum AI system.\"";

const MEMORY: &str = "You get better at helping this user the more you remember about them across \
conversations. When you learn something durable and reusable — who they are (their role, expertise, \
the projects and tools they work with), how they like answers (format, depth, tone, language), their \
recurring workflows and conventions, or a correction or preference they give you — save it with \
the `remember` tool or edit them if already existing (scope 'user' for a personal fact, 'workspace' \
for one the whole team shares).";

const WEB_RESEARCH: &str = "For web research, start with one focused query and a small result limit \
(usually 3–5). Batch only genuinely independent questions; avoid broad overlapping searches, and \
fetch only the pages selected for use. When embedding third-party material in an App, include clear \
attribution and, when appropriate, source links; use concise summaries or adaptations rather than \
reproducing full pages. Source links are citations, not substitutes for requested App screens or \
actions.";

/// Return the complete built-in guidance for an interactive turn. Profile
/// system prompts and dynamic context are separate system messages added by the
/// caller.
pub(crate) fn chat(conversation_mode: bool) -> String {
    let output = if conversation_mode {
        CONVERSATION_OUTPUT
    } else {
        NORMAL_CHAT_OUTPUT
    };
    [
        output,
        UI_AUTHORING_RECIPE,
        APP_AUTHORING,
        AI_DISCLOSURE,
        MEMORY,
        WEB_RESEARCH,
        DELEGATE_GUIDANCE,
    ]
    .join("\n\n")
}

/// Render the current user's profile and recalled memories as dynamic context.
pub(crate) fn user_context(profile: &Profile, recalled: &[String]) -> Option<String> {
    let mut sections = Vec::new();

    if !profile.fields.is_empty() {
        let mut section =
            String::from("Profile of the current user — use it to personalize your answers:\n");
        for (key, value) in &profile.fields {
            let rendered = match value {
                serde_json::Value::String(value) => value.clone(),
                other => other.to_string(),
            };
            section.push_str(&format!("- {key}: {rendered}\n"));
        }
        sections.push(section);
    }

    if !recalled.is_empty() {
        let mut section = String::from("Relevant things you remember about the user:\n");
        for memory in recalled {
            section.push_str(&format!("- {memory}\n"));
        }
        sections.push(section);
    }

    (!sections.is_empty()).then(|| sections.join("\n"))
}

/// Render the workspace skills advertised to this turn as dynamic context.
pub(crate) fn skills_context(skills: &[(String, String)]) -> Option<String> {
    if skills.is_empty() {
        return None;
    }
    let mut section = String::from(
        "Skills available in this workspace — reusable runbooks you can run with the \
         `use_skill` tool. When a request matches one, invoke it (pass the name) and \
         follow the returned instructions:\n",
    );
    for (name, description) in skills {
        if description.is_empty() {
            section.push_str(&format!("- {name}\n"));
        } else {
            section.push_str(&format!("- {name}: {description}\n"));
        }
    }
    Some(section)
}

#[cfg(test)]
mod tests {
    use super::*;
    use catalerum_core::{UserId, WorkspaceId};

    fn profile(pairs: &[(&str, serde_json::Value)]) -> Profile {
        Profile {
            workspace_id: WorkspaceId::new(),
            user_id: UserId::new(),
            fields: pairs
                .iter()
                .map(|(key, value)| (key.to_string(), value.clone()))
                .collect(),
        }
    }

    #[test]
    fn normal_chat_guidance_includes_rich_output_and_standing_rules() {
        let guidance = chat(false);
        for expected in [
            "Markdown",
            "```mermaid",
            "$…$",
            "$$…$$",
            "local app",
            "`present_ui`",
            "internal master-detail flow",
            "list_external_database_connections",
            "never invent a connection, schema, or table name",
            "one focused query",
            "clear attribution",
            "Source links are citations",
            "`remember`",
            "`delegate`",
            "AI-generated",
            "generated by the catalerum AI system",
        ] {
            assert!(guidance.contains(expected), "missing {expected:?}");
        }
    }

    #[test]
    fn chat_guidance_has_a_complete_native_app_authoring_recipe() {
        let guidance = chat(false);
        for expected in [
            "native emerged-UI tools",
            "Never create external HTML, CSS, or app files",
            "`explain_ui_schema`",
            "focused `get_ui_schema` calls",
            "small shell with `present_ui` and a stable `name`",
            "returned `ui_id`",
            "every later `read_ui`, `create_ui_components`, `edit_ui_components`, or `edit_ui`",
            "top-level `ui_id` as `id` or the exact stable `name`",
            "Re-present it with `present_ui` and the stable `name`",
            "Build small sections with `create_ui_components`",
            "Use `edit_ui_components` for a subtree",
            "`edit_ui` for a small targeted patch",
            "When present, `children` is an array and `events` is a map",
            "`bind` only for input components",
            "`{{path}}` interpolation",
            "`ScriptDef` object shaped as `{source:\"...\",runtime?:\"javascript\"}`",
            "Client `before` ClientOps run before the named server script",
            "`catalerum.getState()`",
            "`catalerum.setState()`",
            "Never execute authored JavaScript in the browser",
            "do not retry an unchanged call",
            "self-contained static-data App",
            "unless the user requested an external data source",
            "focused `read_ui` verification, then `present_ui`",
        ] {
            assert!(guidance.contains(expected), "missing {expected:?}");
        }
    }

    #[test]
    fn conversation_guidance_requires_short_plain_text() {
        let guidance = chat(true);
        assert!(guidance.contains("short, concise plain text only"));
        assert!(guidance.contains("read aloud"));
        assert!(!guidance.contains("```mermaid"));
        assert!(guidance.contains("Native App recipe"));
        assert!(guidance.contains("`remember`"));
        assert!(guidance.contains("`delegate`"));
    }

    #[test]
    fn user_context_renders_profile_and_memories() {
        assert!(user_context(&profile(&[]), &[]).is_none());

        let context = user_context(
            &profile(&[
                ("timezone", serde_json::json!("Europe/Berlin")),
                ("focus_hours", serde_json::json!(4)),
            ]),
            &["prefers async standups".to_string()],
        )
        .unwrap();
        assert!(context.contains("- focus_hours: 4\n"));
        assert!(context.contains("- timezone: Europe/Berlin\n"));
        assert!(context.contains("Relevant things you remember about the user"));
        assert!(context.contains("- prefers async standups\n"));
    }

    #[test]
    fn skills_context_lists_names_with_optional_descriptions() {
        assert!(skills_context(&[]).is_none());
        let context = skills_context(&[
            ("summarize".to_string(), "Summarize content.".to_string()),
            ("quiet-one".to_string(), String::new()),
        ])
        .unwrap();
        assert!(context.contains("`use_skill`"));
        assert!(context.contains("- summarize: Summarize content.\n"));
        assert!(context.contains("- quiet-one\n"));
        assert!(!context.contains("- quiet-one:"));
    }
}
