apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalerum-api-wsb
  namespace: catalerum-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: catalerum-api-wsb
subjects:
  - kind: ServiceAccount
    name: catalerum-api
    namespace: catalerum-system
